### PR TITLE
Add hubert robust

### PR DESCRIPTION
**Pull request by nobel861017**
Add a new upstream model.
HuBERT base continually trained with Libri 960 hr with Musan noise, Gaussian noise, and Reverberation.

### CODE REVIEW

**Comment by nobel861017** [comment]
Tested by
```python3
import torch
import s3prl.hub as hub
model = getattr(hub, 'hubert_base_robust_mgr')()
device = 'cuda'
model = model.to(device)
wavs = [torch.randn(160000, dtype=torch.float).to(device) for _ in range(16)]
with torch.no_grad():
    reps = model_0(wavs)["hidden_states"]
```

**Comment by nobel861017** [comment]
Should I modify the README of upstream?

**Comment by leo19941227** [comment]
Thanks @nobel861017 ,

Sure please update the upstream/README

**Comment by nobel861017** [comment]
> Thanks @nobel861017 ,
> 
> Sure please update the upstream/README

I added a row at the bottom of the table.

**Comment by leo19941227** [comment]
You added the same row as the hubert/hubert large ?
Isn't it some kind of robust hubert?

**Comment by nobel861017** [comment]
I'm sorry, I forgot to save the file lol.

**Comment by nobel861017** [comment]
> You added the same row as the hubert/hubert large ? Isn't it some kind of robust hubert?

fixed

**Review by leo19941227 — APPROVED** [review]
Hey @nobel861017,

Thanks, this works!
I am merging this PR.

**Pull request merged**
