### PR TITLE
DDP training for MOSEI

### PR DESCRIPTION
**Pull request by paulhuangkm**
Added DDP training for MOSEI (related to issue #195)

The code has been tested with
 
```
# Training using wav2vec2 as upstream
CUDA_VISIBLE_DEVICES=0,1 python3 -m torch.distributed.launch --nproc_per_node 2 run_downstream.py -m train -u wav2vec2 -d mosei -n Test --upstream_trainable --upstream_feature_selection last_hidden_state
```

Part of the added code is adapted from https://github.com/s3prl/s3prl/issues/188#issuecomment-944946822 and https://github.com/s3prl/s3prl/pull/285

### CODE REVIEW

**Comment by andi611** [comment]
@leo19941227 FYI, these are students from this year's 專題討論 course

**Comment by leo19941227** [comment]
Cool, I will have a look recently.

**Comment by leo19941227** [comment]
Hi @paulhuangkm ,

Thanks for the PR. As you mentioned, this PR depends on #285, I believe a better way to do this would be we first merge #285 and make necessary changes on top of it. Or else, these two PR will essentially conflict.
Could you help with this? Thanks!

**Comment by leo19941227** [comment]
Hi @paulhuangkm ,

Thanks for the PR. As you mentioned, this PR depends on #285, I believe a better way to do this would be we first merge #285 and make necessary changes on top of it. Or else, these two PR will essentially conflict.
Could you help with this? Thanks!

**Comment by paulhuangkm** [comment]
@leo19941227 Sure! What should I do here?

**Comment by leo19941227** [comment]
Cool, thanks @paulhuangkm !
I have merged the PR #285 , could you start from the current new master and test if MOSEI works correctly, and then add the DDP support on top of it?

**Comment by leo19941227** [comment]
There are lots of conflict now, so you might need to forced/rebase your master, or submit a new PR for this. Please select the way which is the most convenient to you.

**Comment by paulhuangkm** [comment]
@leo19941227 No problem! Working on it.

**Comment by leo19941227** [comment]
Cool, many thanks!

**Comment by leo19941227** [comment]
Thanks @paulhuangkm ! This PR looks very nice to me.
Are you ready to merge this? (Since you are still pushing new commits)
If you are ready I think this PR is ready to be merged.

**Comment by paul6678** [comment]
Yes, I did some final adjustments and I think it's ready.

**Comment by paulhuangkm** [comment]
Yes, I did some adjustments and I think it's ready.

**Comment by leo19941227** [comment]
Cool, many thanks!

**Pull request merged**
