### PR TITLE
Add ESPnet Pre-trained HuBERT models as new upstream

### PR DESCRIPTION
**Pull request by ftshijt**
As mentioned in #488, we would like to add the espnet hubert models within the following two submissions. Please feel free to have a check to the implementation.

https://arxiv.org/abs/2306.06672
https://arxiv.org/abs/2309.15317

If the check looks good, will start to add the entry in the doc.

### CODE REVIEW

**Comment by ftshijt** [comment]
I saw the black check is not passed, which might due to version mismatch? I'm using the latest one fyi.

**Comment by leo19941227** [comment]
Hi @ftshijt ,

Yes, the black version is the reason.
We use `22.3.0` as shown here https://github.com/s3prl/s3prl/blob/71b3c6c11b9b8932a28af0dba21e7db664a5dc2c/requirements/dev.txt#L7

The code looks good to me, while I have a minor suggestion is about the `espnet2` version. Would it be nice to indicate the minimum required version of `espnet2` in the `logger.warning`? Or you plan to include another `external_tools/install_espnet.sh` file? (I guess only the PyPi package is required so might not need a shell script, but maybe it is more complicated then I thought)

**Comment by leo19941227** [comment]
Hi @ftshijt ,

Sorry, I am not sure about "we might do have a version issue."
Do you mean the `black` version or `espnet2` version?

**Comment by ftshijt** [comment]
> Hi @ftshijt ,
> 
> Sorry, I am not sure about "we might do have a version issue." Do you mean the `black` version or `espnet2` version?

My apology for confusion made. I was refering to adding a minimum requirement to espnet version.

**Comment by ftshijt** [comment]
Oh, I guess I get the issue. I actually prepared the install_espnet, but did not see that it is excluded to gitignore, so failed to add that in previous commits

**Comment by leo19941227** [comment]
Cool!

**Comment by leo19941227** [comment]
Hi @ftshijt , 

The current state looks good to me. Let's move on to the documentation!
(You may add the author information or update the [change log](https://github.com/s3prl/s3prl#change-log) if you want.)

**Comment by ftshijt** [comment]
Hi @leo19941227 , in case you did not see, I update the doc a few days back. Please let me know if it looks good~ Look forward to using ESPnet hubert from s3prl!

**Comment by leo19941227** [comment]
Hi @ftshijt ,

Sorry! I missed the email. I am now working on this.

**Review by leo19941227 — APPROVED** [review]

**Comment by leo19941227** [comment]
The whole PR looks good to me. I would make the following adjustment after merging and publish the new PyPi package:
- reverting back the conflicted VC doc
- add how to install espnet_hubert in the `logger.warning` of espnet_hubert's import section

**Comment by leo19941227** [comment]
I am launching an experiment for `espnet_hubert_base_iter1` for phoneme recognition, will publish the PyPi package after I can reproduce the PR result.

**Comment by leo19941227** [comment]
I can successfully reproduce `espnet_hubert_base_iter1 ` on PR with test PER: 5.764. Preparing the PyPi package

**Comment by leo19941227** [comment]
The PyPi package is out at https://pypi.org/project/s3prl/0.4.11/
Thanks @ftshijt !
(I am running the espnet ci myself to make sure things won't crash at your side...)

**Comment by ftshijt** [comment]
Many many thanks~

**Pull request merged**
