### PR TITLE
add aamsoftmax for asv

### PR DESCRIPTION
**Pull request by HaibinWu666**

### CODE REVIEW

**Comment by leo19941227** [comment]
Hi @pohanchi long time no see haha
If you have time and are interested, would you like to review this PR?
I will also review it.

**Comment by pohanchi** [comment]
Okay I will finish in this weekday.

**Comment by leo19941227** [comment]
Do you mean weekend?
I thought you are already onboard lol

**Comment by pohanchi** [comment]
I think I will finish it in this Friday.

**Comment by leo19941227** [comment]
Cool!

**Review by pohanchi — APPROVED** [review]
Merge aamsoftmax objective!

**Pull request merged**
