### PR TITLE
Adding author info (Adaptive Spec Augment)

### PR DESCRIPTION
**Pull request by cornliu**
Adding adaptive spec augment function by undergraduate researcher (HW2).

### CODE REVIEW

**Comment by andi611** [comment]
@leo19941227 Special project students are taking credit by adding author info, 
if the format is fine with u I will merge this PR.

**Comment by leo19941227** [comment]
Cool! I think it is nice to add the author info. But adding it at each line is quite weird lol Since  we can know the line author information by git blame.
Can we instead simply add the authors at the top of the file?

**Comment by cornliu** [comment]
I move the author info to the top of the file. Please check if the format is fine for you. Thanks!!!

**Comment by leo19941227** [comment]
Cool! I am good with the format.
If @andi611 is also cool with it, we can merge it.
Thanks for the contribution!

**Pull request merged**
